- name: Converge
  hosts: all
  vars:
    loki_docker_image_version: latest
    loki_docker_memory: 1G
    loki_docker_labels:
      maintainer: me@example.com
    loki_docker_network: internal
    loki_docker_publish_ports:
      - 127.0.0.1:3100:3100
    loki_data_path: /var/lib/loki
    loki_etc_path: /etc/loki
    loki_config: {}
    loki_env_vars:
      APP_TEST_ENV: "true"
  roles:
    - role: ansible-raspberry-loki-docker
      tags: loki
